### ISSUE TITLE
toJava call on future converter causes java.lang.NoClassDefFoundError: scala/concurrent/java8/FuturesConvertersImpl$CF,

### ISSUE THREAD

**Issue by jasongoodwin** [scala/scala-java8-compat#26]
Hey,

on v0.2.0 published to maven,
I've produced a barebones sbt project with only the scala-java8-compat library. 
You can recreate by running sbt test on this project:
https://github.com/jasongoodwin/future-converters-problem

There is a unit test that fails:

    @Test
    public void itShouldNotFail() {
        Future future = promise().future();
        final CompletionStage cs = toJava(future);
    }

It causes this exception

```
[error] Test pong.JavaAskExamplesTest.itShouldNotFail failed: java.lang.NoClassDefFoundError: scala/concurrent/java8/FuturesConvertersImpl$CF, took 0.062 sec
[error]     at scala.compat.java8.FutureConverters$.toJava(FutureConverters.scala:54)
[error]     at scala.compat.java8.FutureConverters.toJava(FutureConverters.scala)
[error]     at pong.JavaAskExamplesTest.itShouldNotFail(JavaAskExamplesTest.java:14)
[error]     ...
[error] Caused by: java.lang.ClassNotFoundException: scala.concurrent.java8.FuturesConvertersImpl$CF
[error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[error]     at java.security.AccessController.doPrivileged(Native Method)
[error]     at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error]     ... 58 more
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error] 	pong.JavaAskExamplesTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 32 s, completed 15-Feb-2015 10:43:38 AM
```

**Comment by retronym** [comment]
Thanks for the report. Looks like the OSGi packaging in our build stripped those classes out of the final JAR. :cry: 

I'll cut a new release as soon as the fix is reviewed and merged.

**Comment by jasongoodwin** [comment]
That's for publishing this so fast.
